// import styles from "./index.module.css";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Toàn đẹp trai</title>
        <meta name="description" content="Generated by create-t3-app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <>
        <div>hihi</div>
        <div>hehe</div>
        <div>cho</div>
        <div>0wrewr</div>
      </>
    </>
  );
};

export default Home;
